name: scrumlab_system_alert_window
description: A flutter plugin to show Truecaller like overlay window, over all other apps along with callback events. Android Go or Android 11 & above, this plugin shows notification bubble, in other android versions, it shows an overlay window.
version: 1.4.2
homepage: https://github.com/scrum-lab/ScrumlabSystemAlertWindow

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: br.com.scrumlab.scrumlab_system_alert_window
        pluginClass: ScrumlabSystemAlertWindowPlugin
      ios:
        package: br.com.scrumlab.scrumlab_system_alert_window
        pluginClass: ScrumlabSystemAlertWindowPlugin

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserratRegular.ttf
        - asset: assets/fonts/montserratSemiBold.ttf
          weight: 700
        - asset: assets/fonts/montserratMedium.ttf
          weight: 800
        - asset: assets/fonts/montserratBold.ttf
          weight: 900